version: 2
jobs:
  build:
    docker:
      - image: node:8.0
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: yarn install --freeze-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run:
          name: Running tests...
          command: yarn test


